- name: Esperar a que cloud-init termine
  command: cloud-init status --wait
  changed_when: false
  failed_when: false
  timeout: 120

- name: Reparar dpkg si quedó interrumpido
  command: dpkg --configure -a
  become: true
  changed_when: false

- name: Actualizar apt cache ignorando errores de repos
  command: apt-get update -o Acquire::AllowInsecureRepositories=true
  changed_when: false
  failed_when: false

- name: Instalar qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Habilitar qemu-guest-agent
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started
