all:
  children:
    reverse_proxy:
      hosts:
        reverse-proxy:
          ansible_host: 172.16.120.10
          ansible_user: root
          ansible_password: "{{ lxc_root_password }}"
          ansible_python_interpreter: /usr/bin/python3
