all:
  hosts:
    localhosts:
      ansible_connection: local
  children:
    reverse_proxy:
      hosts:
        reverse-proxy:
          ansible_host: 172.16.120.10
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
