lxc_root_password: "tu-password-aqui"
certbot_email: "some@email.com"

vhosts:
  - name: service
    domain: service.domain.mx
    backend: X.X.X.X:Y

  - name: minio
    domain: minio.tudominio.mx
    backend: X.X.X.X:Y

qemu_hosts:
  - name: somename
    ip: x.x.x.x

lxc_hosts:
  - name: somename
    ip: x.x.x.x
