- name: Construir inventario dinámico
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/generated.yml
    - ../vars/secrets.yml

  tasks:
    - name: Agregar VMs al grupo qemu
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: qemu
        ansible_become: true
        ansible_become_password: "{{ passwords[item.name] }}"
        ansible_user: "{{ item.user }}"
        ansible_ssh_private_key_file: "/home/tfuser/.ssh/id_ed25519"
      loop: "{{ qemu_hosts }}"

    - name: Agregar LXCs al grupo lxc
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: lxc
        ansible_become: true
        ansible_become_password: "{{ passwords[item.name] }}"
        ansible_user: "{{ item.user }}"
        ansible_ssh_private_key_file: "/home/tfuser/.ssh/id_ed25519"
      loop: "{{ lxc_hosts }}"

# ---- VMs ----
- name: Configurar QEMU Agent en VMs
  hosts: qemu
  become: true
  roles:
    - qemu_agent

# ---- LXC ----
- name: Configuración base en LXC
  hosts: lxc
  become: true

  tasks:
    - name: Instalar paquetes base
      apt:
        name:
          - iproute2
          - net-tools
        state: present
        update_cache: yes
